name: Docker Image CI

on:
  push:
    branches: [ cosign-action ]
  pull_request:
    branches: [ cosign-action ]

jobs:


          
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: copy key
        run: |
          printf ${{ secrets.COSIGNKEY }} > /tmp/cosign.key
        
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mbpf/devops
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Sign image
        run: |
          cosign sign -key /temp/cosign.key mbpf/devops
          
  
